# **Introduction to Pandas**

In [4]:
# import pandas library
# pd is the short name used for pandas

import pandas as pd

print("Pandas imported successfully")

Pandas imported successfully

## **What is pandas?**

In [5]:
# pandas is used to work with table data
# like Excel table or CSV file

print("Pandas helps us work with rows and columns")

Pandas helps us work with rows and columns

**Creating a Series**

In [6]:
# Series = one single column of data

s = pd.Series([10, 20, 30, 40, 50])

print(s)

# Series is like one column
# index is on left
# values are on right

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
# Series with custom index

# we can also give our own labels/index

s2 = pd.Series([90, 85, 88], index=["Math", "English", "Science"])

print(s2)

# custom labels make data more meaningful

Math       90
English    85
Science    88
dtype: int64

## Create a DataFrame

In [8]:
# DataFrame = table with rows and columns

data = {
    "Name": ["Madhu", "Rahul", "Priya", "Arjun", "Neha"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["MSC", "BSc", "BBA", "BCA", "BSc"],
    "Marks": [85, 78, 92, 74, 88]
}

df = pd.DataFrame(data)

print(df)

# dictionary keys become column names
# each list becomes one column
# DataFrame is the main pandas object

    Name  Age Course  Marks
0  Madhu   20    MSC     85
1  Rahul   21    BSc     78
2  Priya   19    BBA     92
3  Arjun   22    BCA     74
4   Neha   20    BSc     88

In [9]:
# Check type

# type() tells what kind of object it is

print(type(df))

# this confirms it is a DataFrame

<class 'pandas.core.frame.DataFrame'>

In [10]:
# View first rows

# head() shows first 5 rows by default

df.head()

# useful for quickly checking big datasets

    Name  Age Course  Marks
0  Madhu   20    MSC     85
1  Rahul   21    BSc     78
2  Priya   19    BBA     92
3  Arjun   22    BCA     74
4   Neha   20    BSc     88

In [11]:
# View last rows

# tail() shows last 5 rows by default

df.tail()

    Name  Age Course  Marks
0  Madhu   20    MSC     85
1  Rahul   21    BSc     78
2  Priya   19    BBA     92
3  Arjun   22    BCA     74
4   Neha   20    BSc     88

In [12]:
# Column names

# columns shows all column names

df.columns

Index(['Name', 'Age', 'Course', 'Marks'], dtype='object')

In [13]:
# Basic info

# info() gives summary
# shows column names, data types, non-null values

df.info()

# very useful for understanding dataset structure

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Course  5 non-null      object
 3   Marks   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [14]:
# Statistical summary

# describe() gives summary of numerical columns

df.describe()

             Age      Marks
count   5.000000   5.000000
mean   20.400000  83.400000
std     1.140175   7.334848
min    19.000000  74.000000
25%    20.000000  78.000000
50%    20.000000  85.000000
75%    21.000000  88.000000
max    22.000000  92.000000

In [15]:
# Select one column

# select one column using column name

# df["Name"]

# Select multiple columns

# select multiple columns using list

df[["Name", "Marks"]]

    Name  Marks
0  Madhu     85
1  Rahul     78
2  Priya     92
3  Arjun     74
4   Neha     88

In [16]:
# Select a row using index

# loc is used to select row by label/index

df.loc[0]

# row 0 means first row

Name      Madhu
Age          20
Course      MSC
Marks        85
Name: 0, dtype: object

In [17]:
# Select multiple rows

# select rows 0 to 2

df.loc[0:2]

# in loc, end value is included

    Name  Age Course  Marks
0  Madhu   20    MSC     85
1  Rahul   21    BSc     78
2  Priya   19    BBA     92

In [18]:
# Select row and specific columns

# select row 1 and 2 with Name and Marks columns

df.loc[1:2, ["Name", "Marks"]]

    Name  Marks
1  Rahul     78
2  Priya     92

In [19]:
# # iloc selects by position number

df.iloc[0]

# loc = label based
# iloc = position based

Name      Madhu
Age          20
Course      MSC
Marks        85
Name: 0, dtype: object

In [20]:
# Filter data

# show students with marks greater than 80

df[df["Marks"] > 85]

# filtering means showing only matching rows

    Name  Age Course  Marks
2  Priya   19    BBA     92
4   Neha   20    BSc     88

In [21]:
# Another filter

# show students whose course is BCA

df[df["Course"] == "MSC"]

    Name  Age Course  Marks
0  Madhu   20    MSC     85

In [22]:
# Multiple conditions

# use & for AND condition
# use brackets around each condition

df[(df["Marks"] > 80) & (df["Course"] == "BSc")]

# & means both conditions must be true

   Name  Age Course  Marks
4  Neha   20    BSc     88

In [23]:
# Add a new column

# create a new column called Pass
# if marks >= 80 then pass = Yes else No

df["Pass"] = ["Yes", "No", "Yes", "No", "Yes"]

df

    Name  Age Course  Marks Pass
0  Madhu   20    MSC     85  Yes
1  Rahul   21    BSc     78   No
2  Priya   19    BBA     92  Yes
3  Arjun   22    BCA     74   No
4   Neha   20    BSc     88  Yes

In [24]:
# Add another calculated column

# add 5 grace marks to every student

df["Updated_Marks"] = df["Marks"] + 5

df

    Name  Age Course  Marks Pass  Updated_Marks
0  Madhu   20    MSC     85  Yes             90
1  Rahul   21    BSc     78   No             83
2  Priya   19    BBA     92  Yes             97
3  Arjun   22    BCA     74   No             79
4   Neha   20    BSc     88  Yes             93

In [25]:
# Find average marks

# mean() gives average

df["Marks"].mean()

np.float64(83.4)

In [26]:
# Find maximum marks

# max() gives highest value

df["Marks"].max()

# Find minimum marks

# min() gives lowest value

# df["Marks"].min()

92

In [27]:
# Count values

# value_counts() counts repeated values

df["Course"].value_counts()

Course
BSc    2
MSC    1
BBA    1
BCA    1
Name: count, dtype: int64

In [28]:
# Sort values

# sort by marks in ascending order

df.sort_values("Marks")

    Name  Age Course  Marks Pass  Updated_Marks
3  Arjun   22    BCA     74   No             79
1  Rahul   21    BSc     78   No             83
0  Madhu   20    MSC     85  Yes             90
4   Neha   20    BSc     88  Yes             93
2  Priya   19    BBA     92  Yes             97

In [29]:
# Sort descending

# sort by marks from highest to lowest

df.sort_values("Marks", ascending=False)

    Name  Age Course  Marks Pass  Updated_Marks
2  Priya   19    BBA     92  Yes             97
4   Neha   20    BSc     88  Yes             93
0  Madhu   20    MSC     85  Yes             90
1  Rahul   21    BSc     78   No             83
3  Arjun   22    BCA     74   No             79

In [30]:
# Rename a column

# rename column name

df.rename(columns={"Marks": "Score"})

# original df will not change unless reassigned or inplace used

    Name  Age Course  Score Pass  Updated_Marks
0  Madhu   20    MSC     85  Yes             90
1  Rahul   21    BSc     78   No             83
2  Priya   19    BBA     92  Yes             97
3  Arjun   22    BCA     74   No             79
4   Neha   20    BSc     88  Yes             93

In [31]:
# Update renamed column permanently

# save renamed column permanently

df = df.rename(columns={"Marks": "Score"})

df

    Name  Age Course  Score Pass  Updated_Marks
0  Madhu   20    MSC     85  Yes             90
1  Rahul   21    BSc     78   No             83
2  Priya   19    BBA     92  Yes             97
3  Arjun   22    BCA     74   No             79
4   Neha   20    BSc     88  Yes             93

In [32]:
# Check missing values

# isnull() checks missing values
# sum() counts them column wise

df.isnull().sum()

Name             0
Age              0
Course           0
Score            0
Pass             0
Updated_Marks    0
dtype: int64

In [33]:
# Create missing values example

# make one value missing for practice

df.loc[2, "Score"] = None

df

    Name  Age Course  Score Pass  Updated_Marks
0  Madhu   20    MSC   85.0  Yes             90
1  Rahul   21    BSc   78.0   No             83
2  Priya   19    BBA    NaN  Yes             97
3  Arjun   22    BCA   74.0   No             79
4   Neha   20    BSc   88.0  Yes             93

In [34]:
# Check missing values again

# now one value is missing in Score column

df.isnull().sum()

Name             0
Age              0
Course           0
Score            1
Pass             0
Updated_Marks    0
dtype: int64

In [35]:
# Fill missing value

# fill missing value with 0

df["Score"] = df["Score"].fillna(0)

df

# fillna() is used to replace missing values

    Name  Age Course  Score Pass  Updated_Marks
0  Madhu   20    MSC   85.0  Yes             90
1  Rahul   21    BSc   78.0   No             83
2  Priya   19    BBA    0.0  Yes             97
3  Arjun   22    BCA   74.0   No             79
4   Neha   20    BSc   88.0  Yes             93

In [36]:
# Drop a column

# drop one column
# axis=1 means column

df.drop("Pass", axis=1)

    Name  Age Course  Score  Updated_Marks
0  Madhu   20    MSC   85.0             90
1  Rahul   21    BSc   78.0             83
2  Priya   19    BBA    0.0             97
3  Arjun   22    BCA   74.0             79
4   Neha   20    BSc   88.0             93

In [37]:
# Save file as CSV

# save DataFrame to CSV file

df.to_csv("student_data.csv", index=False)

print("CSV file saved successfully")

# index=False removes extra index column in file

CSV file saved successfully

# Read CSV again

In [38]:
# read the saved CSV file

new_df = pd.read_csv("student_data.csv")

new_df.head()

# now students understand full cycle:
# create → view → edit → save → read

    Name  Age Course  Score Pass  Updated_Marks
0  Madhu   20    MSC   85.0  Yes             90
1  Rahul   21    BSc   78.0   No             83
2  Priya   19    BBA    0.0  Yes             97
3  Arjun   22    BCA   74.0   No             79
4   Neha   20    BSc   88.0  Yes             93

In [39]:
# Home task:

# practice dataset

data2 = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Tablet"],
    "Price": [55000, 500, 1200, 9000, 15000],
    "Quantity": [5, 25, 10, 7, 8]
}

shop_df = pd.DataFrame(data2)

shop_df

    Product  Price  Quantity
0    Laptop  55000         5
1     Mouse    500        25
2  Keyboard   1200        10
3   Monitor   9000         7
4    Tablet  15000         8

In [40]:
# answer

# add total column

shop_df["Total"] = shop_df["Price"] * shop_df["Quantity"]

shop_df

    Product  Price  Quantity   Total
0    Laptop  55000         5  275000
1     Mouse    500        25   12500
2  Keyboard   1200        10   12000
3   Monitor   9000         7   63000
4    Tablet  15000         8  120000

# **Topics covered**

In [42]:
# “Pandas is used to work with table data in Python, just like Excel but with code.”

display("Covered topics:")
print("1. Import pandas")
print("2. Series")
print("3. DataFrame")
print("4. head, tail, shape, columns, info")
print("5. selecting rows and columns")
print("6. filtering")
print("7. adding columns")
print("8. basic analysis")
print("9. sorting")
print("10. missing values")
print("11. saving and reading CSV")

'Covered topics:'

1. Import pandas
2. Series
3. DataFrame
4. head, tail, shape, columns, info
5. selecting rows and columns
6. filtering
7. adding columns
8. basic analysis
9. sorting
10. missing values
11. saving and reading CSV